# Generated by Django 5.2.8 on 2026-01-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='category',
            field=models.CharField(choices=[('flower', 'Flower'), ('wedding', 'Wedding'), ('workshop', 'Workshop'), ('shopplant', 'Shop Plant')], default='flower', max_length=20),
            preserve_default=False,
        ),
    ]
