# Generated by Django 5.2.8 on 2026-02-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='description',
            field=models.TextField(default='Refund request'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refund',
            name='email',
            field=models.EmailField(default='Refund request', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refund',
            name='issue_type',
            field=models.CharField(choices=[('Damaged', 'Damaged Item'), ('Wrong', 'Wrong Item'), ('Missing', 'Missing Item'), ('Other', 'Other')], default='Refund request', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refund',
            name='name',
            field=models.CharField(default='Refund request', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refund',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='refund_photos/'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Refunded', 'Refunded')], default='Pending', max_length=20),
        ),
    ]
