# Generated by Django 5.2.8 on 2026-02-04 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_refund_description_refund_email_refund_issue_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='damage_photo',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='reason',
        ),
        migrations.AlterField(
            model_name='refund',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='issue_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='refund',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='refunds/'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
